=== IFPB-PRPIPG/periodicos-ifpb/lib/pkp/dtd/bic21qualifiers.dtd
<!--
  * bic21qualifiers.dtd
  *
  * Copyright (c) 2013-2015 Simon Fraser University Library
  * Copyright (c) 2000-2015 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for BIC 2.1 Subject Qualifier lists.
  *
  -->
<!ELEMENT qualifiers (qualifier+)>
<!ELEMENT qualifier EMPTY>
	<!ATTLIST qualifier 
		code CDATA #REQUIRED
		text CDATA #REQUIRED>

=== IFPB-PRPIPG/periodicos-ifpb/lib/pkp/locale/es_ES/bic21qualifiers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qualifiers SYSTEM "../../dtd/bic21qualifiers.dtd">
<!--
  * locale/es_ES/bic21qualifiers.xml
  *
  * Copyright BIC and Nielsen Book Services Ltd 2010
  *
  * Credits: http://pkp.sfu.ca/wiki/index.php?title=OJS:_Spanish_%28es_ES%29
  *
  * localized list of BIC 2.1 Subject Qualifiers
  * Reference:  http://www.bic.org.uk/7/BIC-Standard-Subject-Categories
  -->

<qualifiers>
	<qualifier code="1D" text="Europa" />
	<qualifier code="1DB" text="Islas Británicas" />
	<qualifier code="1DBK" text="Reino Unido, Gran Bretaña" />
	<qualifier code="1DBKE" text="Inglaterra" />
	<qualifier code="1DBKEA" text="Anglia Oriental" />
	<qualifier code="1DBKEAC" text="Cambridgeshire" />
	<qualifier code="1DBKEAL" text="Lincolnshire" />
	<qualifier code="1DBKEAN" text="Norfolk" />
	<qualifier code="1DBKEAS" text="Suffolk" />
	<qualifier code="1DBKEAX" text="Essex" />
	<qualifier code="1DBKEM" text="Midlands" />
	<qualifier code="1DBKEMD" text="Derbyshire y Distrito de los Picos" />
	<qualifier code="1DBKEMF" text="Herefordshire" />
	<qualifier code="1DBKEML" text="Leicestershire" />
	<qualifier code="1DBKEMM" text="Northamptonshire" />
	<qualifier code="1DBKEMN" text="Nottinghamshire" />
	<qualifier code="1DBKEMP" text="Shropshire" />
	<qualifier code="1DBKEMR" text="Rutland" />
	<qualifier code="1DBKEMS" text="Staffordshire" />
	<qualifier code="1DBKEMT" text="Worcestershire" />
	<qualifier code="1DBKEMW" text="Warwickshire, Midlands occidentales" />
	<qualifier code="1DBKEN" text="Noroeste de Inglaterra" />
	<qualifier code="1DBKENC" text="Cheshire" />
	<qualifier code="1DBKENL" text="Lancashire, Gran Mánchester, Merseyside" />
	<qualifier code="1DBKENM" text="Cumbria y Distrito de los Lagos" />
	<qualifier code="1DBKES" text="Sur y sureste de Inglaterra" />
	<qualifier code="1DBKESB" text="Berkshire" />
	<qualifier code="1DBKESD" text="Bedfordshire" />
	<qualifier code="1DBKESF" text="Oxfordshire" />
	<qualifier code="1DBKESH" text="Hampshire" />
	<qualifier code="1DBKESK" text="Kent" />
	<qualifier code="1DBKESL" text="Londres, Gran Londres" />
	<qualifier code="1DBKESR" text="Surrey" />
	<qualifier code="1DBKEST" text="Hertfordshire" />
	<qualifier code="1DBKESU" text="Buckinghamshire" />
	<qualifier code="1DBKESW" text="Isla de Wight" />
	<qualifier code="1DBKESX" text="Sussex" />
	<qualifier code="1DBKEW" text="Suroeste de Inglaterra" />
	<qualifier code="1DBKEWC" text="Cornualles" />
	<qualifier code="1DBKEWD" text="Devon" />
	<qualifier code="1DBKEWG" text="Gloucestershire" />
	<qualifier code="1DBKEWS" text="Somerset, Brístol" />
	<qualifier code="1DBKEWT" text="Dorset" />
	<qualifier code="1DBKEWW" text="Wiltshire" />
	<qualifier code="1DBKEY" text="Norte y noreste de Inglaterra" />
	<qualifier code="1DBKEYD" text="Durham" />
	<qualifier code="1DBKEYK" text="Yorkshire" />
	<qualifier code="1DBKEYN" text="Northumberland, Tyne y Wear" />
	<qualifier code="1DBKN" text="Irlanda del Norte" />
	<qualifier code="1DBKS" text="Escocia" />
	<qualifier code="1DBKSB" text="Tierras bajas de Escocia y Fronteras" />
	<qualifier code="1DBKSC" text="Escocia central" />
	<qualifier code="1DBKSH" text="Norte de Escocia, Tierras Altas e islas" />
	<qualifier code="1DBKSHF" text="Islas Orcadas" />
	<qualifier code="1DBKSHJ" text="Islas Setelanda" />
	<qualifier code="1DBKSHL" text="Islas Occidentales, Hébridas Exteriores" />
	<qualifier code="1DBKSHQ" text="Isla de Skye" />
	<qualifier code="1DBKW" text="Gales" />
	<qualifier code="1DBKWC" text="Gales del Centro" />
	<qualifier code="1DBKWN" text="Gales del Norte" />
	<qualifier code="1DBKWS" text="Gales del Sur" />
	<qualifier code="1DBKWV" text="Suroeste de Gales" />
	<qualifier code="1DBKX" text="Islas del Canal" />
	<qualifier code="1DBKZ" text="Isla de Man" />
	<qualifier code="1DBR" text="Irlanda" />
	<qualifier code="1DD" text="Europa Occidental continental" />
	<qualifier code="1DDB" text="Bélgica" />
	<qualifier code="1DDF" text="Francia" />
	<qualifier code="1DDFC" text="Córcega" />
	<qualifier code="1DDFM" text="Mónaco" />
	<qualifier code="1DDL" text="Luxemburgo" />
	<qualifier code="1DDN" text="Países Bajos" />
	<qualifier code="1DF" text="Europa central" />
	<qualifier code="1DFA" text="Austria" />
	<qualifier code="1DFG" text="Alemania" />
	<qualifier code="1DFGE" text="Alemania Oriental, RDA" />
	<qualifier code="1DFGW" text="Alemania Occidental" />
	<qualifier code="1DFH" text="Suiza" />
	<qualifier code="1DFHA" text="Alpes" />
	<qualifier code="1DFL" text="Liechtenstein" />
	<qualifier code="1DN" text="Europa del Norte, Escandinavia" />
	<qualifier code="1DNC" text="Islandia" />
	<qualifier code="1DND" text="Dinamarca" />
	<qualifier code="1DNDF" text="Islas Feroe" />
	<qualifier code="1DNF" text="Finlandia" />
	<qualifier code="1DNN" text="Noruega" />
	<qualifier code="1DNS" text="Suecia" />
	<qualifier code="1DS" text="Europa del Sur" />
	<qualifier code="1DSE" text="España" />
	<qualifier code="1DSEB" text="Islas Baleares" />
	<qualifier code="1DSEP" text="Pirineos" />
	<qualifier code="1DSG" text="Gibraltar" />
	<qualifier code="1DSM" text="Malta" />
	<qualifier code="1DSN" text="Andorra" />
	<qualifier code="1DSP" text="Portugal" />
	<qualifier code="1DST" text="Italia" />
	<qualifier code="1DSTA" text="Cerdeña" />
	<qualifier code="1DSTC" text="Sicilia" />
	<qualifier code="1DSU" text="San Marino" />
	<qualifier code="1DSV" text="Vaticano" />
	<qualifier code="1DV" text="Europa del Este" />
	<qualifier code="1DVC" text="Chipre" />
	<qualifier code="1DVG" text="Grecia" />
	<qualifier code="1DVGS" text="Islas griegas" />
	<qualifier code="1DVGSC" text="Creta" />
	<qualifier code="1DVH" text="Hungría" />
	<qualifier code="1DVK" text="Antigua Checoslovaquia" />
	<qualifier code="1DVKC" text="República Checa" />
	<qualifier code="1DVKS" text="Eslovaquia" />
	<qualifier code="1DVP" text="Polonia" />
	<qualifier code="1DVT" text="Turquía" />
	<qualifier code="1DVU" text="Antigua Unión Soviética, URSS (Europa)" />
	<qualifier code="1DVUA" text="Rusia" />
	<qualifier code="1DVUAC" text="Chechenia" />
	<qualifier code="1DVUB" text="Belarús (Bielorrusia)" />
	<qualifier code="1DVUC" text="Letonia" />
	<qualifier code="1DVUE" text="Estonia" />
	<qualifier code="1DVUF" text="Lituania" />
	<qualifier code="1DVUG" text="Georgia" />
	<qualifier code="1DVUK" text="Ucrania" />
	<qualifier code="1DVUM" text="Moldavia" />
	<qualifier code="1DVUR" text="Armenia" />
	<qualifier code="1DVUZ" text="Azerbaiyán" />
	<qualifier code="1DVW" text="Europa suroriental" />
	<qualifier code="1DVWA" text="Albania" />
	<qualifier code="1DVWB" text="Bulgaria" />
	<qualifier code="1DVWR" text="Rumanía" />
	<qualifier code="1DVWY" text="Yugoslavia y antigua Yugoslavia" />
	<qualifier code="1DVWYB" text="Bosnia y Herzegovina" />
	<qualifier code="1DVWYC" text="Croacia" />
	<qualifier code="1DVWYK" text="Kosovo" />
	<qualifier code="1DVWYM" text="Macedonia" />
	<qualifier code="1DVWYN" text="Montenegro" />
	<qualifier code="1DVWYS" text="Serbia" />
	<qualifier code="1DVWYV" text="Eslovenia" />
	<qualifier code="1F" text="Asia" />
	<qualifier code="1FB" text="Oriente Próximo y Medio" />
	<qualifier code="1FBH" text="Israel" />
	<qualifier code="1FBJ" text="Jordania" />
	<qualifier code="1FBL" text="Líbano" />
	<qualifier code="1FBN" text="Irán" />
	<qualifier code="1FBP" text="Palestina" />
	<qualifier code="1FBQ" text="Irak" />
	<qualifier code="1FBS" text="Siria" />
	<qualifier code="1FBX" text="Península arábiga" />
	<qualifier code="1FBXB" text="Baréin" />
	<qualifier code="1FBXK" text="Kuwait" />
	<qualifier code="1FBXM" text="Omán" />
	<qualifier code="1FBXQ" text="Catar" />
	<qualifier code="1FBXS" text="Arabia Saudí" />
	<qualifier code="1FBXU" text="Emiratos Árabes Unidos" />
	<qualifier code="1FBXY" text="Yemen" />
	<qualifier code="1FC" text="Asia Central" />
	<qualifier code="1FCA" text="Afganistán" />
	<qualifier code="1FCD" text="Tayikistán (Tadzhikistán)" />
	<qualifier code="1FCK" text="Kirguistán (Kirguizia)" />
	<qualifier code="1FCS" text="Siberia" />
	<qualifier code="1FCT" text="Turkmenistán" />
	<qualifier code="1FCU" text="Uzbekistán" />
	<qualifier code="1FCZ" text="Kazajistán" />
	<qualifier code="1FK" text="Subcontinente indio" />
	<qualifier code="1FKA" text="India" />
	<qualifier code="1FKAH" text="Himalaya" />
	<qualifier code="1FKAS" text="Islas Andamán y Nicobar" />
	<qualifier code="1FKB" text="Bangladés" />
	<qualifier code="1FKH" text="Bután" />
	<qualifier code="1FKN" text="Nepal" />
	<qualifier code="1FKP" text="Pakistán" />
	<qualifier code="1FKS" text="Sri Lanka (Ceilán)" />
	<qualifier code="1FM" text="Asia suroriental" />
	<qualifier code="1FMB" text="Myanmar (Birmania)" />
	<qualifier code="1FMC" text="Camboya" />
	<qualifier code="1FML" text="Laos" />
	<qualifier code="1FMM" text="Malasia" />
	<qualifier code="1FMN" text="Indonesia" />
	<qualifier code="1FMNB" text="Bali" />
	<qualifier code="1FMNT" text="Timor Oriental" />
	<qualifier code="1FMNX" text="Borneo" />
	<qualifier code="1FMP" text="Filipinas" />
	<qualifier code="1FMR" text="Brunéi" />
	<qualifier code="1FMS" text="Singapur" />
	<qualifier code="1FMT" text="Tailandia" />
	<qualifier code="1FMV" text="Vietnam" />
	<qualifier code="1FP" text="Asia Oriental, Lejano Oriente" />
	<qualifier code="1FPC" text="China" />
	<qualifier code="1FPCH" text="Hong Kong" />
	<qualifier code="1FPCM" text=" Macao" />
	<qualifier code="1FPCT" text="Tíbet" />
	<qualifier code="1FPCW" text="Taiwán" />
	<qualifier code="1FPJ" text="Japón" />
	<qualifier code="1FPK" text="Corea" />
	<qualifier code="1FPKN" text="Corea del Norte" />
	<qualifier code="1FPKS" text="Corea del Sur" />
	<qualifier code="1FPM" text="Mongolia" />
	<qualifier code="1H" text="África" />
	<qualifier code="1HB" text="África septentrional" />
	<qualifier code="1HBA" text="Argelia" />
	<qualifier code="1HBC" text="Chad" />
	<qualifier code="1HBE" text="Egipto" />
	<qualifier code="1HBEN" text="Río Nilo" />
