=== IFPB-PRPIPG/periodicos-ifpb/plugins/generic/objectsForReview/xml/object.dtd
<!--
  * object.dtd
  *
  * DTD for review object information.
  * Used by the objects for review plugin functionality.
  *
  -->
<!ELEMENT object (objectType, roleSelectionOptions, objectMetadata)>
<!ATTLIST object
	locale CDATA #IMPLIED>
<!ELEMENT objectType (#PCDATA)>
<!ATTLIST objectType
	key CDATA #REQUIRED>
<!ELEMENT objectMetadata (metadata*)>
<!ELEMENT roleSelectionOptions (selectionOption+)>
<!ELEMENT metadata (name, selectionOptions?)>
<!ATTLIST metadata
	type (smallTextField | singleLineTextBox | extendedTextBox | checkBoxes | radioButtons | dropDownBox | roleDropDownBox | languageDropDownBox | coverPage) "singleLineTextBox"
	required (true | false) "false"
	display (true | false) "false"
	key CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT selectionOptions (selectionOption+)>
<!ELEMENT selectionOption (#PCDATA)>

=== IFPB-PRPIPG/periodicos-ifpb/plugins/generic/objectsForReview/xml/reviewObjects/letter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE object SYSTEM "../object.dtd">
<object locale="en_US">
	<objectType key="letter">plugins.generic.objectsForReview.object.letter</objectType>
	<roleSelectionOptions>
		<selectionOption>plugins.generic.objectsForReview.object.letter.person.author</selectionOption>
		<selectionOption>plugins.generic.objectsForReview.object.letter.person.contributor</selectionOption>
		<selectionOption>plugins.generic.objectsForReview.object.letter.person.recipient</selectionOption>
	</roleSelectionOptions>
	<objectMetadata>
	<metadata type="singleLineTextBox" required="false" display="false" key="letter_type">
		<name>plugins.generic.objectsForReview.object.letter.type</name>
	</metadata>
	</objectMetadata>	
</object>
